spring:
  datasource:
    url: jdbc:h2:~/jpa-ex-jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # ! create, update, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
