package jpaWithApi.jpashop.repository;

import jpaWithApi.jpashop.domain.member.Member;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface MemberRepository extends JpaRepository<Member, Long> {


    /**
     * Auto generated By Spring Data Jpa: `select m from Member m where m.name = ?`
     * @param name
     */
    List<Member> findByName(String name);
}
