spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/data-jpa;DATABASE_TO_UPPER=false;
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create # ! create, update, none
    properties:
      hibernate:
#        show_sql: true ## SQL은 안보이게합시다.
        format_sql: true
        default_batch_fetch_size: 100
  #    open-in-view: false # 영속성 Context 범위 설정 (* default: `true` / *`false` = DB Connection은 @Trasaction 내에서만 유효) => 강의 참고 https://www.inflearn.com/course/lecture?courseSlug=%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-JPA-API%EA%B0%9C%EB%B0%9C-%EC%84%B1%EB%8A%A5%EC%B5%9C%EC%A0%81%ED%99%94&unitId=24339&tab=curriculum

  devtools:
    restart:
      additional-paths: /src/main/resources
      poll-interval: 50 # ClassPath 변경에 대한 Polling 주기
      quiet-period: 10 # 재시작 트리거 전, Class Path 변경 지연 시간


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # 지저분해서 주석처리
